Repository lejard-h/chopper, pull requests merged in 2023-05, with the labels that each got.

#417 :arrow_up: Bump Dart SDK constraint to ">=2.17.0 <4.0.0"
  .github/workflows/dart.yml
  chopper/pubspec.yaml
  chopper_built_value/pubspec.yaml
  chopper_built_value/test/data.g.dart
  chopper_built_value/test/serializers.g.dart
  chopper_generator/lib/src/generator.dart
  chopper_generator/pubspec.yaml
  example/lib/built_value_resource.chopper.dart
  example/lib/built_value_resource.g.dart
  example/lib/built_value_serializers.g.dart
  example/lib/json_decode_service.activator.g.dart
  example/lib/json_decode_service.vm.g.dart
  example/lib/json_decode_service.worker.g.dart
  example/pubspec.yaml
  tool/ci.sh
Labels: enhancement

#419 :green_heart: Fix CI publish
  .github/workflows/publish.yml
  .github/workflows/publish_dry_run.yml
  chopper/.DS_Store
  chopper/CHANGELOG.md
  chopper_built_value/CHANGELOG.md
  chopper_generator/CHANGELOG.md
  tool/publish.sh
Labels: CI

#420 :bookmark: release 6.1.2 (2nd attempt)
  .github/workflows/publish.yml
  .github/workflows/publish_dry_run.yml
  chopper/.DS_Store
  tool/publish.sh
Labels: release

#421 :green_heart: Fix CI publish credentials
  .github/workflows/publish.yml
Labels: ci

#422 :bookmark: release v6.1.2 (3rd attempt)
  .github/workflows/publish.yml
Labels: release

#423 :green_heart: Fix CI coverage reporting
  .github/workflows/dart.yml
  chopper/mono_pkg.yaml
  chopper_built_value/mono_pkg.yaml
  mono_repo.yaml
  tool/ci.sh
  tool/coverage.sh
Labels: ci

#424 :construction_worker: only run CI publish / --dry-run when a package's version changes
  .github/workflows/publish.yml
  .github/workflows/publish_dry_run.yml
  tool/compare_versions.dart
  tool/pubspec.yaml
Labels: ci

#425 :bug: fix publish CI to run only on push
  .github/workflows/publish.yml
Labels: bug, ci

#427 :green_heart: fix publish workflow
  .github/workflows/publish.yml
  chopper_generator/lib/src/generator.dart
Labels: bug, ci

#428 :twisted_rightwards_arrows: merge publish workflow fix to master
  .github/workflows/publish.yml
  chopper_generator/lib/src/generator.dart
Labels: bug, ci

#430 Adding follow redirects to toHttpRequest
  chopper/lib/src/request.dart
Labels: bug

#435 Add MultipartRequest log to CurlInterceptor
  chopper/lib/src/interceptor.dart
  chopper/test/interceptors_test.dart
Labels: enhancement

#434 :green_heart: add cleanup step to publish workflow
  .github/workflows/publish.yml
Labels: ci
