Repository lejard-h/chopper, pull requests merged in 2023-01, with the labels that each got.

#399 Configurable HttpLoggingInterceptor
  chopper/lib/chopper.dart
  chopper/lib/src/http_logging_interceptor.dart
  chopper/lib/src/interceptor.dart
  chopper/test/http_logging_interceptor_test.dart
  chopper/test/interceptors_test.dart
  interceptors.md
Labels: enhancement

#400 Made apply headers field name case insensitive.
  chopper/lib/src/utils.dart
  chopper/test/converter_test.dart
  chopper/test/utils_test.dart
Labels: bug

#403 :bulb: Clean up code in comments
  chopper/lib/src/annotations.dart
  chopper/lib/src/utils.dart
Labels: documentation
