Repository lejard-h/chopper, pull requests merged in 2023-08, with the labels that each got.

#465 :bookmark: release v7.0.1
  .github/workflows/dart.yml
  chopper/CHANGELOG.md
  chopper/example/definition.chopper.dart
  chopper/lib/src/base.dart
  chopper/lib/src/interceptor.dart
  chopper/lib/src/utils.dart
  chopper/pubspec.yaml
  chopper/test/base_test.dart
  chopper/test/test_service.chopper.dart
  chopper_built_value/mono_pkg.yaml
  chopper_generator/CHANGELOG.md
  chopper_generator/lib/src/generator.dart
  chopper_generator/mono_pkg.yaml
  chopper_generator/pubspec.yaml
  chopper_generator/test/test_service.chopper.dart
  example/lib/built_value_resource.chopper.dart
  example/lib/json_serializable.chopper.dart
  mono_repo.yaml
  tool/ci.sh
Labels: release

#470 :sparkles: HttpLoggingInterceptor: allow to pass custom logger
  chopper/lib/src/http_logging_interceptor.dart
Labels: enhancement

#471 :construction_worker: use yq to manipulate pubspec.yaml in publish CI
  .github/workflows/publish.yml
  .github/workflows/publish_dry_run.yml
  chopper/pubspec.yaml
  chopper_built_value/pubspec.yaml
  chopper_generator/pubspec.yaml
  tool/publish.sh
Labels: cd

#472 :bookmark: release v7.0.2
  .github/dependabot.yml
  .github/workflows/dart.yml
  .github/workflows/publish.yml
  .github/workflows/publish_dry_run.yml
  chopper/CHANGELOG.md
  chopper/lib/src/http_logging_interceptor.dart
  chopper/pubspec.yaml
  chopper_built_value/pubspec.yaml
  chopper_generator/pubspec.yaml
  mono_repo.yaml
  tool/publish.sh
Labels: release

#475 :sparkles: Attach request/response to interceptor log lines
  chopper/lib/src/chopper_log_record.dart
  chopper/lib/src/http_logging_interceptor.dart
Labels: enhancement

#476 :bookmark: release v7.0.3
  chopper/CHANGELOG.md
  chopper/lib/src/chopper_log_record.dart
  chopper/lib/src/http_logging_interceptor.dart
  chopper/pubspec.yaml
Labels: release

#477 :twisted_rightwards_arrows: post release branch sync
  chopper/CHANGELOG.md
  chopper/pubspec.yaml
Labels: sync

#482 :bookmark: release v7.0.4
  chopper/CHANGELOG.md
  chopper/lib/chopper.dart
  chopper/lib/src/chopper_log_record.dart
  chopper/pubspec.yaml
Labels: release

#483 :twisted_rightwards_arrows: post release branch sync
  chopper/CHANGELOG.md
  chopper/pubspec.yaml
Labels: sync

#485 :bookmark: release chopper_generator v7.0.2
  chopper_generator/CHANGELOG.md
  chopper_generator/pubspec.yaml
Labels: release

#486 :twisted_rightwards_arrows: post release branch sync
  chopper_generator/CHANGELOG.md
  chopper_generator/pubspec.yaml
Labels: sync

#490 :bookmark: release chopper v7.0.5
  chopper/CHANGELOG.md
  chopper/README.md
  chopper/pubspec.yaml
Labels: release

#491 :twisted_rightwards_arrows: post release branch sync
  chopper/CHANGELOG.md
  chopper/pubspec.yaml
Labels: sync

#493 Adding support for top level variables
  chopper/lib/src/annotations.dart
  chopper/test/base_test.dart
  chopper/test/ensure_build_test.dart
  chopper/test/test_service_variable.chopper.dart
  chopper/test/test_service_variable.dart
  chopper_generator/lib/src/generator.dart
  chopper_generator/test/ensure_build_test.dart
  chopper_generator/test/test_service_variable.chopper.dart
  chopper_generator/test/test_service_variable.dart
Labels: enhancement
