Repository lejard-h/chopper, pull requests merged in 2023-10, with the labels that each got.

#507 :rotating_light: correct static analysis suppression of *.chopper.dart files
  chopper/analysis_options.yaml
  chopper/example/definition.chopper.dart
  chopper/test/test_service.chopper.dart
  chopper/test/test_service_variable.chopper.dart
  chopper_built_value/analysis_options.yaml
  chopper_generator/Makefile
  chopper_generator/analysis_options.yaml
  chopper_generator/lib/src/generator.dart
  chopper_generator/test/test_service.chopper.dart
  chopper_generator/test/test_service_variable.chopper.dart
  example/analysis_options.yaml
  example/lib/built_value_resource.chopper.dart
  example/lib/json_serializable.chopper.dart
Labels: bug

#508 :bug: remove charset from http request headers when the body is in bytes
  chopper/lib/src/request.dart
  chopper/test/base_test.dart
Labels: bug

#509 :construction_worker: update mono_repo
  .github/workflows/dart.yml
  tool/ci.sh
Labels: ci

#510 :construction_worker: create Github release when publishing package
  .github/workflows/publish.yml
  .github/workflows/publish_dry_run.yml
Labels: ci, cd

#511 :bookmark: release chopper v7.0.7 and chopper_generator v7.0.5
  .github/workflows/dart.yml
  .github/workflows/publish.yml
  .github/workflows/publish_dry_run.yml
  chopper/CHANGELOG.md
  chopper/analysis_options.yaml
  chopper/example/definition.chopper.dart
  chopper/lib/src/request.dart
  chopper/pubspec.yaml
  chopper/test/base_test.dart
  chopper/test/test_service.chopper.dart
  chopper/test/test_service_variable.chopper.dart
  chopper_built_value/analysis_options.yaml
  chopper_generator/CHANGELOG.md
  chopper_generator/Makefile
  chopper_generator/analysis_options.yaml
  chopper_generator/lib/src/generator.dart
  chopper_generator/pubspec.yaml
  chopper_generator/test/test_service.chopper.dart
  chopper_generator/test/test_service_variable.chopper.dart
  example/analysis_options.yaml
  example/lib/built_value_resource.chopper.dart
  example/lib/json_serializable.chopper.dart
  tool/ci.sh
Labels: release

#512 :green_heart: fix publish workflow permissions
  .github/workflows/publish.yml
Labels: cd

#513 :bookmark: release v7.0.7+1
  chopper/CHANGELOG.md
  chopper/pubspec.yaml
  chopper_built_value/CHANGELOG.md
  chopper_built_value/pubspec.yaml
  chopper_generator/CHANGELOG.md
  chopper_generator/pubspec.yaml
Labels: release

#514 :twisted_rightwards_arrows: post release branch sync
  .github/workflows/publish.yml
  chopper/CHANGELOG.md
  chopper/pubspec.yaml
  chopper_built_value/CHANGELOG.md
  chopper_built_value/pubspec.yaml
  chopper_generator/CHANGELOG.md
  chopper_generator/pubspec.yaml
Labels: sync

#516 :sparkles: encode DateTime query parameters as ISO8601
  chopper/lib/src/utils.dart
  chopper/test/base_test.dart
  chopper/test/test_service.chopper.dart
  chopper/test/test_service.dart
Labels: bug, enhancement

#517 :bookmark: release chopper v7.0.8
  chopper/CHANGELOG.md
  chopper/lib/src/utils.dart
  chopper/pubspec.yaml
  chopper/test/base_test.dart
  chopper/test/test_service.chopper.dart
  chopper/test/test_service.dart
Labels: release

#518 :twisted_rightwards_arrows: post release branch sync
  chopper/CHANGELOG.md
  chopper/pubspec.yaml
Labels: sync

#520 Fix incorrect url generation when using new baseurl
  chopper/test/base_test.dart
  chopper/test/ensure_build_test.dart
  chopper/test/test_service_base_url.chopper.dart
  chopper/test/test_service_base_url.dart
  chopper_generator/lib/src/generator.dart
Labels: bug

#521 :bookmark: release chopper_generator v7.0.6
  chopper/test/base_test.dart
  chopper/test/ensure_build_test.dart
  chopper/test/test_service_base_url.chopper.dart
  chopper/test/test_service_base_url.dart
  chopper_generator/CHANGELOG.md
  chopper_generator/lib/src/generator.dart
  chopper_generator/pubspec.yaml
Labels: release

#522 :twisted_rightwards_arrows: post release branch sync
  chopper_generator/CHANGELOG.md
  chopper_generator/pubspec.yaml
Labels: sync

#529 Added mock mixins of Chopper components.
  chopper/lib/src/base.dart
  chopper/lib/src/chopper_log_record.dart
  chopper/lib/src/request.dart
  chopper/lib/src/response.dart
Labels: enhancement

#527 Added success/failure callback hooks to Authenticator.
  chopper/lib/src/authenticator.dart
  chopper/lib/src/base.dart
  chopper/test/authenticator_test.dart
  chopper/test/fake_authenticator.dart
Labels: enhancement

#531 :bookmark: release chopper v7.0.9
  chopper/CHANGELOG.md
  chopper/Makefile
  chopper/lib/src/authenticator.dart
  chopper/lib/src/base.dart
  chopper/lib/src/chopper_log_record.dart
  chopper/lib/src/request.dart
  chopper/lib/src/response.dart
  chopper/pubspec.yaml
  chopper/test/authenticator_test.dart
  chopper/test/fake_authenticator.dart
  chopper_built_value/Makefile
  chopper_built_value/pubspec.yaml
  chopper_generator/pubspec.yaml
Labels: release
