Repository lejard-h/chopper, pull requests merged in 2024-01, with the labels that each got.

#542 :twisted_rightwards_arrows: post release branch sync
  chopper/CHANGELOG.md
  chopper/pubspec.yaml
  chopper_generator/CHANGELOG.md
  chopper_generator/pubspec.yaml
Labels: sync

#543 Helper function for fetching errors of specific type
  chopper/lib/src/response.dart
  chopper/test/base_test.dart
  chopper/test/fixtures/error_fixtures.dart
Labels: enhancement

#549 :bug: fix chopper_generator regression introduced in #534
  chopper/test/test_service.chopper.dart
  chopper/test/test_service.dart
  chopper_generator/lib/src/generator.dart
  chopper_generator/test/test_service.chopper.dart
  chopper_generator/test/test_service.dart
Labels: bug

#555 :bookmark: release chopper v7.1.0+1
  chopper/CHANGELOG.md
  chopper/pubspec.yaml
Labels: release

#556 :twisted_rightwards_arrows: post release branch sync
  chopper/CHANGELOG.md
  chopper/pubspec.yaml
  chopper_generator/CHANGELOG.md
  chopper_generator/pubspec.yaml
Labels: sync

#557 :construction_worker: use Dependabot to check for workflow action updates
  .github/dependabot.yml
Labels: ci, dependencies

#562 :sparkles: add option to override build_extension
  chopper_generator/lib/src/builder_factory.dart
  chopper_generator/pubspec.yaml
  faq.md
Labels: enhancement

#563 :bookmark: release chopper_generator v7.1.1
  .github/dependabot.yml
  chopper_generator/CHANGELOG.md
  chopper_generator/lib/src/builder_factory.dart
  chopper_generator/pubspec.yaml
Labels: release

#565 :twisted_rightwards_arrows: post release branch sync
  chopper_generator/CHANGELOG.md
  chopper_generator/pubspec.yaml
  faq.md
Labels: sync

#566 :rewind: revert faq.md
  faq.md
Labels: documentation

#568 :bookmark: release chopper v7.1.1
  chopper/CHANGELOG.md
  chopper/lib/src/annotations.dart
  chopper/pubspec.yaml
  faq.md
Labels: release

#569 :twisted_rightwards_arrows: post release branch sync
  chopper/CHANGELOG.md
  chopper/pubspec.yaml
Labels: sync
