Repository lejard-h/chopper, pull requests merged in 2024-04, with the labels that each got.

#592 :zap: use qs_dart for query string encoding
  chopper/analysis_options.yaml
  chopper/lib/chopper.dart
  chopper/lib/src/annotations.dart
  chopper/lib/src/list_format.dart
  chopper/lib/src/request.dart
  chopper/lib/src/utils.dart
  chopper/pubspec.yaml
  chopper/test/base_test.dart
  chopper/test/test_service.chopper.dart
  chopper/test/test_service.dart
  chopper/test/test_service_base_url.chopper.dart
  chopper/test/test_service_base_url.dart
  chopper/test/test_service_variable.chopper.dart
  chopper/test/test_service_variable.dart
  chopper/test/test_without_response_service.chopper.dart
  chopper/test/test_without_response_service.dart
  chopper/test/utils_test.dart
  chopper_generator/analysis_options.yaml
  chopper_generator/lib/src/generator.dart
  chopper_generator/lib/src/utils.dart
  chopper_generator/pubspec.yaml
  chopper_generator/test/test_service.chopper.dart
  chopper_generator/test/test_service.dart
  chopper_generator/test/test_service_variable.chopper.dart
  chopper_generator/test/test_service_variable.dart
  chopper_generator/test/test_without_response_service.chopper.dart
  chopper_generator/test/test_without_response_service.dart
  example/analysis_options.yaml
Labels: enhancement

#594 :arrow_up: update Github actions
  .github/workflows/dart.yml
  .github/workflows/publish.yml
  .github/workflows/publish_dry_run.yml
Labels: ci

#595 :bookmark: release v7.4.0
  .github/workflows/dart.yml
  .github/workflows/publish.yml
  .github/workflows/publish_dry_run.yml
  chopper/CHANGELOG.md
  chopper/analysis_options.yaml
  chopper/lib/chopper.dart
  chopper/lib/src/annotations.dart
  chopper/lib/src/list_format.dart
  chopper/lib/src/request.dart
  chopper/lib/src/utils.dart
  chopper/pubspec.yaml
  chopper/test/base_test.dart
  chopper/test/test_service.chopper.dart
  chopper/test/test_service.dart
  chopper/test/test_service_base_url.chopper.dart
  chopper/test/test_service_base_url.dart
  chopper/test/test_service_variable.chopper.dart
  chopper/test/test_service_variable.dart
  chopper/test/test_without_response_service.chopper.dart
  chopper/test/test_without_response_service.dart
  chopper/test/utils_test.dart
  chopper_generator/CHANGELOG.md
  chopper_generator/analysis_options.yaml
  chopper_generator/lib/src/generator.dart
  chopper_generator/lib/src/utils.dart
  chopper_generator/pubspec.yaml
  chopper_generator/test/test_service.chopper.dart
  chopper_generator/test/test_service.dart
  chopper_generator/test/test_service_variable.chopper.dart
  chopper_generator/test/test_service_variable.dart
  chopper_generator/test/test_without_response_service.chopper.dart
  chopper_generator/test/test_without_response_service.dart
  example/analysis_options.yaml
Labels: release

#596 :twisted_rightwards_arrows: post release branch sync
  chopper/CHANGELOG.md
  chopper/pubspec.yaml
  chopper_generator/CHANGELOG.md
  chopper_generator/pubspec.yaml
Labels: sync

#597 :arrow_up: update cli_script to 1.0.0 (was 0.3.1)
  tool/pubspec.yaml
Labels: ci, dependencies, cd

#547 :sparkles: Restructure interceptors
  chopper/lib/chopper.dart
  chopper/lib/src/annotations.dart
  chopper/lib/src/authenticator.dart
  chopper/lib/src/base.dart
  chopper/lib/src/chain/call.dart
  chopper/lib/src/chain/chain.dart
  chopper/lib/src/chain/interceptor_chain.dart
  chopper/lib/src/chopper_exception.dart
  chopper/lib/src/chopper_http_exception.dart
  chopper/lib/src/converters.dart
  chopper/lib/src/extensions.dart
  chopper/lib/src/interceptors/authenticator_interceptor.dart
  chopper/lib/src/interceptors/curl_interceptor.dart
  chopper/lib/src/interceptors/headers_interceptor.dart
  chopper/lib/src/interceptors/http_call_interceptor.dart
  chopper/lib/src/interceptors/http_logging_interceptor.dart
  chopper/lib/src/interceptors/interceptor.dart
  chopper/lib/src/interceptors/internal_interceptor.dart
  chopper/lib/src/interceptors/request_converter_interceptor.dart
  chopper/lib/src/interceptors/request_stream_interceptor.dart
  chopper/lib/src/interceptors/response_converter_interceptor.dart
  chopper/test/authenticator_test.dart
  chopper/test/base_test.dart
  chopper/test/chain/authenticator_interceptor_test.dart
  chopper/test/chain/interceptor_chain_test.dart
  chopper/test/chain/request_converter_interceptor_test.dart
  chopper/test/chain/response_converter_interceptor_test.dart
  chopper/test/client_test.dart
  chopper/test/converter_test.dart
  chopper/test/form_test.dart
  chopper/test/helpers/fake_chain.dart
  chopper/test/http_logging_interceptor_test.dart
  chopper/test/interceptors_test.dart
  chopper/test/json_test.dart
  chopper/test/multipart_test.dart
  example/bin/main_json_serializable.dart
  example/bin/main_json_serializable_squadron_worker_pool.dart
  faq.md
  interceptors.md
Labels: enhancement

#598 :bookmark: pre-release v8.0.0-rc.1
  chopper/CHANGELOG.md
  chopper/lib/chopper.dart
  chopper/lib/src/annotations.dart
  chopper/lib/src/authenticator.dart
  chopper/lib/src/base.dart
  chopper/lib/src/chain/call.dart
  chopper/lib/src/chain/chain.dart
  chopper/lib/src/chain/interceptor_chain.dart
  chopper/lib/src/chopper_exception.dart
  chopper/lib/src/chopper_http_exception.dart
  chopper/lib/src/converters.dart
  chopper/lib/src/extensions.dart
  chopper/lib/src/interceptors/authenticator_interceptor.dart
  chopper/lib/src/interceptors/curl_interceptor.dart
  chopper/lib/src/interceptors/headers_interceptor.dart
  chopper/lib/src/interceptors/http_call_interceptor.dart
  chopper/lib/src/interceptors/http_logging_interceptor.dart
  chopper/lib/src/interceptors/interceptor.dart
  chopper/lib/src/interceptors/internal_interceptor.dart
  chopper/lib/src/interceptors/request_converter_interceptor.dart
  chopper/lib/src/interceptors/request_stream_interceptor.dart
  chopper/lib/src/interceptors/response_converter_interceptor.dart
  chopper/pubspec.yaml
  chopper/test/authenticator_test.dart
  chopper/test/base_test.dart
  chopper/test/chain/authenticator_interceptor_test.dart
  chopper/test/chain/interceptor_chain_test.dart
  chopper/test/chain/request_converter_interceptor_test.dart
  chopper/test/chain/response_converter_interceptor_test.dart
  chopper/test/client_test.dart
  chopper/test/converter_test.dart
  chopper/test/form_test.dart
  chopper/test/helpers/fake_chain.dart
  chopper/test/http_logging_interceptor_test.dart
  chopper/test/interceptors_test.dart
  chopper/test/json_test.dart
  chopper/test/multipart_test.dart
  chopper_generator/CHANGELOG.md
  chopper_generator/pubspec.yaml
  example/bin/main_json_serializable.dart
  example/bin/main_json_serializable_squadron_worker_pool.dart
  faq.md
  interceptors.md
  tool/pubspec.yaml
Labels: pre-release

#599 :twisted_rightwards_arrows: post pre-release branch sync
  chopper/CHANGELOG.md
  chopper/pubspec.yaml
  chopper_generator/CHANGELOG.md
  chopper_generator/pubspec.yaml
Labels: sync
